### ISSUE TITLE
Build tests intermittently failing on Travis

### ISSUE THREAD

**Issue by jonlay** [wearehanno/oskar#26] opened 2015-10-27 23:03 UTC
There shouldn't be any reason that a change to the README makes Travis unhappy: https://travis-ci.org/wearehanno/oskar/builds/87770241

There must be some sort of transient condition which is causing tests to fail sometimes. Seems like it would be sensible to debug this, as it'll give us a greater likelihood of identifying the other issues here and there.

**Comment by marcelkalveram** [comment] 2015-10-28 08:32
I've seen this as well. I guess it has something to do with the timeout methods in the tests and that some methods run in asynchronous order and because of this lead to different results every now and then. I'll investigate further.

**Comment by marcelkalveram** [comment] 2015-10-28 09:09
Looks like the tests are not failing anymore after I made the two failing tests run before the others.

**Comment by jonlay** [comment] 2015-10-28 09:09
For now :wink:

**Comment by jonlay** [comment] 2015-10-28 09:21
I believe this is not actually fixed :disappointed: 

https://travis-ci.org/wearehanno/oskar/builds/87847965

**Comment by marcelkalveram** [comment] 2015-12-25 11:52
The error seems to have occured because the two running builds were accessing the same database. I also couldn't reproduce the errors locally and they didn't make any sense. Since I couldn't find any way to use separate DBs I removed the second build for node version 0.11. I don't think it's necessary anyway.

**Comment by jonlay** [comment] 2015-12-28 02:39
Unfortunately this is still failing when it shouldn't, like for README changes here: https://travis-ci.org/wearehanno/oskar/builds/99040802

**Comment by marcelkalveram** [comment] 2016-04-27 10:49
I've limited the number of concurrent builds on Travis to 1, hoping that it's gonna solve it. It's definitely something I cannot reproduce locally, so I'm gonna close this for now. The last two builds have been successful and the tests are all passing.

**Closed by marcelkalveram** 2016-04-27 10:49 UTC
Labels: bug
